### ISSUE TITLE
Incomplete path in directions (BloodHound: setting up Neo4j)

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#10]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224746

**Describe the problem**
![image](https://user-images.githubusercontent.com/1383363/234384979-31b6aef3-e78e-4179-b5f7-b2dedc046bdb.png)

**Comment by 7MinSec** [comment]
Excellent catch.  Fixed.
