### ISSUE TITLE
More specific Hashcat directions needed for *Dumping and cracking Active Directory hashes*

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#11]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224757

**Describe the problem**

Lab step is simply as follows:

![image](https://user-images.githubusercontent.com/1383363/234390073-af110cd3-ef6d-4313-ba80-595cc828b1ad.png)

But `crackme.csv` is in the Mimikatz folder, `hashcat.exe` is in a different folder, and even the `rockyou.txt` file is in the `Wordlists` folder.

If this is intentional to challenge students a bit, it's fine. Otherwise I'd recommend making the steps more explicit.

**Comment by 7MinSec** [comment]
Added changes so that the explicit paths to everything makes more sense.
