### ISSUE TITLE
*Abusing SQL services* needs more detail for HFS.exe usage

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#15]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46806226

**Describe the problem**
For inexperienced users (such as myself), adding the directions to click Menu -> Add Files (such as the following) would help greatly:
![image](https://user-images.githubusercontent.com/1383363/234423052-5e1dd92a-504f-43ae-ad48-a7dc53d2b0c2.png)

**Comment by 7MinSec** [comment]
Your wish = my command
![image](https://user-images.githubusercontent.com/17596787/234688737-88f909c5-6bcd-40a9-b3ce-b82803328519.png)
