### ISSUE TITLE
Older JtR reference in closing thoughts

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#16]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224763

**Describe the problem**
Should be Hashcat linked here (https://hashcat.net/hashcat/), not JtR.

![image](https://user-images.githubusercontent.com/1383363/234436292-ab0cdc48-7622-426c-9704-fd2fbc3c577f.png)

**Comment by 7MinSec** [comment]
Got it.  Will fix that and also add Impacket.

**Comment by 7MinSec** [comment]
All links and the PDF....FIXED!
