### ISSUE TITLE
Leftover reference from old lab

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#19]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224723

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
instructions say "PT-DC01" actual server name is "tt-dc01"

**Expected behavior**
names should be the same

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/234450142-9d17b5c9-383e-4705-b150-a2bdd2f4f30a.png)
![image](https://user-images.githubusercontent.com/22823269/234450203-9b285e25-cb47-4cdc-816e-779c82732173.png)

**Additional context**

**Comment by hackern0v1c3** [comment]
Quiz answers also start with PT instead of TT

**Comment by 7MinSec** [comment]
Fixed and fixed!
