### ISSUE TITLE
"Relaying hashes from SQL" exercise isn't finished

### ISSUE THREAD

**Issue by 7MinSec** [7MinSec/LPLITE#2]
The curriculum itself needs to be written, and I can't seem to get [Inveigh relay](https://github.com/Kevin-Robertson/Inveigh) to work even if I follow guides like [this one](https://infinitelogins.com/2020/11/16/capturing-relaying-net-ntlm-hashes-without-kali-linux-using-inveigh/) or [this one](https://www.adamcouch.co.uk/ntlmv2-relaying-in-windows-with-powershell-and-inveigh/).

Our pal Jeff McJunkin recommends trying out [PortBender](https://github.com/praetorian-inc/PortBender).

**Comment by jeffmcjunkin** [comment]
Apparently https://github.com/CCob/lsarelayx is even easier, as it's a standalone executable and doesn't need a "real" C2 like Cobalt Strike to run it.

**Comment by 7MinSec** [comment]
The lsarelayx looks awesome but it also seems like it has to be used in combo with ntlmrelayx - and I don't know if ntlmrelayx plays nice in Windows.  I'll have to try that.

**Comment by 7MinSec** [comment]
As an alternative, this standalone version of impacket binaries looked promising (https://github.com/ropnop/impacket_static_binaries) but I hit some issues at runtime (https://github.com/ropnop/impacket_static_binaries/issues/8).

Thinking out loud, I could have the dbadmin account have a slightly more crackable password and have folks get DA that way, but I'd REALLY like to PTH as that's more fun since students will have already done a few cracking exercises by the time they get to this point.

**Comment by 7MinSec** [comment]
The section "relaying hashes from SQL" is now fully baked - both from a testing it out in real time perspective, as well as a curriculum perspective!
