### ISSUE TITLE
Asreproast broken link

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#20]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224730

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
Then link to here [ASREPRoasting](https://www.harmj0y.net/blog/activedirectory/roasting-as-reps/) doesn't work.

**To Reproduce**
1. Click on the link labeled "ASREPRoasting"

**Expected behavior**
The link should send you to a valid website

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/234453783-6b411e24-945f-426d-aaea-d941d6a5807c.png)
![image](https://user-images.githubusercontent.com/22823269/234453821-c684c7a9-6e13-4698-a9c8-6dbba8dbe7db.png)

**Comment by 7MinSec** [comment]
Fixed to https://harmj0y.medium.com/roasting-as-reps-e6179a65216b!
