### ISSUE TITLE
AMSI bypass instructions

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#22]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224728

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
From my experience amsi.fail just kinda doesn't work anymore.  Also the file "c:\users\public\pentest-tools\amsibypass.txt" doesn't seem to be helpful so maybe it can be removed.  The github link at the end of the page does work but people might need some handholding to get it working.  Setting up http server etc.

**To Reproduce**
1. Go to amsi.fail
2. Try a bypass and watch it fail
3. Repeat from step 1

**Expected behavior**
Student should be able to bypass amsi without a lot of interactive hand holding.

**Comment by 7MinSec** [comment]
Thank you sir!  The instructions have now been expanded on to show, step by step, how to leverage that article to create the 1.txt and 2.txt file and main.ps1 and get HFS setup....all the things.
