### ISSUE TITLE
minor detail with hashcat command syntax

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#25]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224737

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
When running the hashcat command to crack the kerberoast and asreproast hashes the hash files won't be in the same dir as the hashcat .exe because it was extracted to its own sub folder.  So copy pasting the command from the instructions wont work.  Instead of this
`hashcat kerberoast.txt ..\wordlists\rockyou.txt`
You need this
`hashcat ..\kerberoast.txt ..\wordlists\rockyou.txt`
Or you need to copy paste kerberoast.txt into the new hashcat directory

**To Reproduce**
1. dump roasted hashese to c:\users\public.pentest-tools dir
2. follow instructions to extract hashcat to the hashcat subfolder
3. cd to c:\users\public.pentest-tools or c:\users\public.pentest-tools\hashcat-6.2.6\
4. run hashcat kerberoast.txt ..\wordlists\rockyou.txt

**Comment by 7MinSec** [comment]
Ok I think in class I'll just have students copy these hashes right into whatever their `hashcat` dir is.  That way they only have to type _one_ long path (when they have to reference `c:\blah\blah\wordlists\rockyou.txt`)
