### ISSUE TITLE
incorrect path to bloodhound

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#26]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224748

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
The instructions say to navigate to `C:\users\public\pentest-tools\AD\Bloodhound-win32-x64`
But the correct path is `C:\Users\Public\pentest-tools\BloodHound-win32-x64`

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/234981900-f01567e2-2b08-4a0b-bb06-d279b8702b2a.png)
![image](https://user-images.githubusercontent.com/22823269/234981951-db0e562e-f2b6-484b-a9c7-a0233ae623bf.png)

**Comment by 7MinSec** [comment]
Excellent.  Fixed.
