### ISSUE TITLE
Incorect hamburger instructions 🍔

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#27]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224749

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
Instructions say hamburger icon is in upper right but it's in the upper left

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/234982823-dda129e0-c3ff-4177-afad-d3d8becd166c.png)
![image](https://user-images.githubusercontent.com/22823269/234982910-03c4cd15-c38a-4c67-b296-6c730de48747.png)

**Comment by 7MinSec** [comment]
Nice one.  Thanks.  Fixed.
