### ISSUE TITLE
incorrect path for hashcat command

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#28]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224757

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
The path to the wordlist in the hashcat command is incorrect.  It says `hashcat -m 1000 crackme.csv ..\rockyou.txt --username`
It should say `hashcat.exe -m 1000 crackme.csv ..\wordlists\rockyou.txt --username`

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/235226556-55cd5e0f-202a-4433-a665-878fdca73284.png)

**Comment by hackern0v1c3** [comment]
Occurs again a few lines later
![image](https://user-images.githubusercontent.com/22823269/235226760-7ea86912-7e60-406b-b97a-6932ff1287cf.png)

**Comment by 7MinSec** [comment]
Corrected!
