### ISSUE TITLE
multitool dir doesnt exist

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#29]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224758

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
The path to cme is listed as `C:\users\public\pentest-tools\multitool` but it's actually `C:\users\public\pentest-tools`

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/235227468-f953ff7e-1f25-4752-bb95-a2dcc0353948.png)

**Comment by 7MinSec** [comment]
Fixy McFixleton.
