### ISSUE TITLE
Impacket hijacked the reg command

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#30]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224759

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
When trying to run the reg query command in the instructions the impacket reg tool runs instead.  It has different syntax so the command fails

**To Reproduce**
1. Open cmd
2. In any directory try running the command from the instructions `reg query HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest /v UseLogonCredential`
3. You'll receive an error message

**Expected behavior**
Either the syntax in the instructions should be for the Impacket reg command or the standard windows reg command should run

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/235229369-0a6a0284-542e-4a1e-a353-88c02dec6fdb.png)
![image](https://user-images.githubusercontent.com/22823269/235229589-fe761f34-49e2-49fb-9689-7b513218d817.png)

**Comment by 7MinSec** [comment]
Wow that's annoying.  It hijacks PING as well.  I think I can just prioritize c:\windows\system32 in the path probably.  Or maybe script it:

http://johnatten.com/2014/12/07/adding-and-editing-path-environment-variables-in-windows/

**Comment by 7MinSec** [comment]
Ok it looks like the broader sweeping fix is to open up environment variables and move the `windows\system32` path to the top:

![envfix1](https://user-images.githubusercontent.com/17596787/236691039-db68c16d-ccec-4bb4-8853-0a11b89e13d5.png)
![envfix2](https://user-images.githubusercontent.com/17596787/236691046-3269c8d4-e42a-480c-8b70-1096fceab1c7.png)

For now, I took a suggestion from someone on our livestream and just changed the reference to `reg` to be `reg.exe` in the curriculum and that does the trick.
