### ISSUE TITLE
pwn town reference

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#31]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224759

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
Instructions reference PT-IT01 instead of TT-IT01

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/235231467-82fdac11-3762-4dcf-a651-4a6c51486a6f.png)

**Comment by 7MinSec** [comment]
Good heavens you have a sharp eye.

*Singing: "And he's watching the beta test curriculum with the eyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyye of the tiger!"*

Fixed.
