### ISSUE TITLE
Link doesnt work 🦀

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#32]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224760

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
The link to the "Deadliest Catch" show doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/235232157-0cde5ab5-8883-4ed5-9e5b-bfd3e143988d.png)
![image](https://user-images.githubusercontent.com/22823269/235232225-375a45c0-7acf-4cf0-95bc-2eb8217591b8.png)

**Comment by 7MinSec** [comment]
HOLY SCHNIKES you are thorough.  Got this critical link fixed!  Good "catch."  Get it?  See what I did there?  I said good "catch" in reference to the show and/or fishing.  And I heard you like fishing so I made that pun.  That's why this is funny.

I need sleep.
