### ISSUE TITLE
Didn't receive an error

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#33]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224760

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
The instructions say that I should receive an error when powershell remoting to tt-it01 using my student credentials.  I didn't receive an error and remoting is working.

**Screenshots**
Instructions
![image](https://user-images.githubusercontent.com/22823269/235232770-7936aa43-3e71-46c1-8620-66d8ee850799.png)
Actual
![image](https://user-images.githubusercontent.com/22823269/235232815-597a6079-3f33-46dd-8efc-b7781f17b7b5.png)

**Comment by hackern0v1c3** [comment]
None of these instructions on the same page applied either.  I didn't need to make any changes for powershell remoting to just work.
![image](https://user-images.githubusercontent.com/22823269/235233065-f2cbb045-f8e4-425a-8203-6170b1b44540.png)

**Comment by 7MinSec** [comment]
Nice catch.  Yeah this is a disconnect on my part from the beta testing folks to the live class.  In the live class what I do right before this point is strip everybody's DA creds away so that they are mere mortals and we have to manually config our lab machines to be able to remote into *tt-it01*.
