### ISSUE TITLE
dont open a command prompt

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#34]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224760

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
Instructions say `1. Open a command prompt`.  But we are in a powershell remoting session.  No need for this step.

**Screenshots**
![image](https://user-images.githubusercontent.com/22823269/235233640-043c9452-2edd-403c-b590-68423fec04bd.png)

**Comment by hackern0v1c3** [comment]
Also step 2 says type powershell and hit Enter.  But we are already in powershell remoted to the machine.  No need for this step either.

**Comment by 7MinSec** [comment]
Great catches. Fixed.

![image](https://user-images.githubusercontent.com/17596787/236690356-dee2951e-7321-441c-8895-8e60a5c4b31c.png)
