### ISSUE TITLE
Mimikatz not sure if bug

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#35]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
*i.e. https://7minsec.teachable.com/courses/x/y/z*
https://7minsec.teachable.com/courses/2053747/lectures/46224760

**Describe the problem**
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
When I ram mimikatz against the lsass dump I only got creds for the computer account.  Not sure if there is supposed to be some automated account login that I should have captured.  Or if you just manually do some login at this point for people to capture.

**Comment by 7MinSec** [comment]
Good call sir.  In class what I do while everybody's getting PowerShell remote'd into _tt-it01_ is I login to that server with another DA user so that those creds are captured with mimi later.

*P.S. this made me go back and redo the whole exercise to make sure it worked - thanks!*
