### ISSUE TITLE
Minor typo for subnet

### ISSUE THREAD

**Issue by hackern0v1c3** [7MinSec/LPLITE#36]
Where is the problem happening
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
i.e. https://7minsec.teachable.com/courses/x/y/z
https://7minsec.teachable.com/courses/2053747/lectures/46808970

Describe the problem
*i.e. "There's a typo on the third line" or "The second paragraph mentions a tool that's not there."
The network is described as `10.0.7.0/x` but it should be `10.0.7.0/24`.  Maybe you meant `10.0.7.x/24`

Screenshots
![image](https://user-images.githubusercontent.com/22823269/235239993-7c84a6c0-8ea1-456d-8318-c9789a897742.png)

**Comment by 7MinSec** [comment]
Sharp eyes.  Fixed.
