### ISSUE TITLE
Day 1, Bypass AMSI page, import-module powerup.ps1 should be ./powerup.ps1

### ISSUE THREAD

**Issue by Xoke** [7MinSec/LPLITE#37]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224728*

**Describe the problem**
Line 15 says 'typing import-module powerup.ps1 which fails.  It should be ./powerup.ps1 (like the image shows)

OK I'm going to be rude and skip the rest of the stuff, as that should be good enough for you to figure it out :)

**Comment by 7MinSec** [comment]
Cheers.  Fixed.
