### ISSUE TITLE
Day 2 Inveigh gender confusion?

### ISSUE THREAD

**Issue by Xoke** [7MinSec/LPLITE#38]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224745

**Describe the problem**
Typo - "At a high level, here's what's happening:" then talking about Brian's Laptop, then 'her machine' and ' so sends her a "Nope!"'.
Typo - "OMg, pick me" should be OMG
Typo - Brian''s -> Brian's

**Comment by Xoke** [comment]
Also on that page it says open powershell to run an exe...

Lets see this in action!
    At a **PowerShell** prompt, navigate to C:\users\public\pentest-tools.
    Now run **Inveigh -?** to view all the different command line options.

**Comment by 7MinSec** [comment]
Thanks!  Fixed everything but the "OMG" as I like to use "OMg" = "Oh my gosh."  :-)
