### ISSUE TITLE
Teh typos

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#4]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
![image](https://user-images.githubusercontent.com/1383363/234360740-32ea3b08-925c-4d34-b7ec-b81658c30966.png)

Inside PDF at https://7minsec.teachable.com/courses/2053747/lectures/46224753

Presumably more typoes are in this thread

**Comment by jeffmcjunkin** [comment]
Same PDF as above: 
![image](https://user-images.githubusercontent.com/1383363/234361160-c2eed696-b002-49ac-b271-efe022747307.png)

**Comment by jeffmcjunkin** [comment]
https://7minsec.teachable.com/courses/2053747/lectures/46224719
![image](https://user-images.githubusercontent.com/1383363/234361557-2d9f59e4-456b-4918-89d7-cecbf193931c.png)

"to be A movie star"

**Comment by jeffmcjunkin** [comment]
Old reference to `PWN.TOWN` in **BloodHound: mapping attack paths** step (https://7minsec.teachable.com/courses/2053747/lectures/46224749)
![image](https://user-images.githubusercontent.com/1383363/234386570-985eaf67-fe1b-4ce1-9119-719d9833fee1.png)

**Comment by jeffmcjunkin** [comment]
Typtoes in *Pass-the-hash attacks*:
![image](https://user-images.githubusercontent.com/1383363/234390903-281fee9a-8c2c-4932-b189-4c4c3f5e2c8c.png)

As written, the directions don't work: 
![image](https://user-images.githubusercontent.com/1383363/234391045-0d2aa038-cdf7-42b7-81e1-a41e2045e086.png)

**Comment by jeffmcjunkin** [comment]
Another old pwntown reference in https://7minsec.teachable.com/courses/2053747/lectures/46224760: 
![image](https://user-images.githubusercontent.com/1383363/234391866-7e14755d-977a-4826-841d-4aacb31ffa22.png)

**Comment by jeffmcjunkin** [comment]
Small typo in `comsvcs.dll` directions inside *Stealing passwords with mimikatz* / https://7minsec.teachable.com/courses/2053747/lectures/46224760: 
![image](https://user-images.githubusercontent.com/1383363/234392878-49a60f96-c155-4c3f-b7f5-aab51fd4cde8.png)

**Comment by jeffmcjunkin** [comment]
ARGH! This one was frustrating. `Minidump` as written in directions should be `MiniDump` as shown in the screenshot, otherwise `rundll32.exe` will give an error: 
![image](https://user-images.githubusercontent.com/1383363/234394614-7e76489d-4a57-4b3a-b5c0-670e438e9868.png)

Worse yet, the error doesn't show up via the `Enter-PSSession`, so it's just a confusing situation unless a student fixes the command for running locally and tests that way. 
![image](https://user-images.githubusercontent.com/1383363/234394768-169ba66c-e2c8-4b66-8bfc-baec73b06824.png)

**Comment by jeffmcjunkin** [comment]
https://7minsec.teachable.com/courses/2053747/lectures/46806226

![image](https://user-images.githubusercontent.com/1383363/234424531-4fa4bbc6-96a1-4b2a-98e7-58376d981fdd.png)

**Comment by 7MinSec** [comment]
Everything fixed but the Bloodhound sample pic.  Will fix that as soon as burn-and-rebuild process is done.

**Comment by 7MinSec** [comment]
Aaaaaand SCENE!
