### ISSUE TITLE
Quotes and exclamation

### ISSUE THREAD

**Issue by project7io** [7MinSec/LPLITE#42]
![image](https://user-images.githubusercontent.com/47162864/236977026-21b410c1-b126-423d-ad42-348f39684e0c.png)

On the Welcome tab under Privilege Escalation, should it be "shell"! instead of "shell!"?

**Comment by 7MinSec** [comment]
I think we're good according to https://grammarpartyblog.com/2012/07/30/inside-or-outside-question-marks-exclamation-points-and-quotation-marks/:

````
If the quote is a question or exclamation, the punctuation mark goes inside the quotation marks.
````
