### ISSUE TITLE
Active Directory nickel tour - mismatch between lab and quiz

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#6]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224724

**Describe the problem**
Incorrect Domain Admins group vs quiz:
![image](https://user-images.githubusercontent.com/1383363/234366135-be97d7f8-79cf-4907-abc8-14f1cfd977c2.png)

![image](https://user-images.githubusercontent.com/1383363/234366273-ea98af26-cee0-4f01-9030-f0c875847d90.png)

**Expected behavior**
They should match.

**Comment by 7MinSec** [comment]
Another wonderful catch.  Brian was a domain admin for PwnTown, but must've gotten let go because he wasn't part of the Tangent Town acquisition I guess.  

Fixed.
