### ISSUE TITLE
Dumping and cracking Active Directory hashes: CMD.exe (admin)

### ISSUE THREAD

**Issue by jaustin1** [7MinSec/LPLITE#60]
CMD.EXE must be an elevated prompt here. Otherwise, the student is not able to get into debug mode.

You probably know the answer: there are lots of ways! Mimikatz can do this in a pretty straightforward way for us, so lets do this:

    Navigate to C:\users\public\pentest-tools\mimikatz\x64.

    Type mimikatz.exe and press Enter.

![image](https://github.com/7MinSec/LPLITE/assets/20890498/693731c4-090c-474e-aeaf-fe154994d921)
![image](https://github.com/7MinSec/LPLITE/assets/20890498/c4eafa1c-c145-4e72-b93e-22278fbadf51)

**Comment by 7MinSec** [comment]
Added the first step of spawning an elevated cmd.exe.
