### ISSUE TITLE
Running CME (is it finished?)

### ISSUE THREAD

**Issue by jaustin1** [7MinSec/LPLITE#63]
Whenever I ran CME, I never got the sign of completion: new command prompt. I had to hit ENTER a few times to get a new command prompt or wait 5 min or so.

![image](https://github.com/7MinSec/LPLITE/assets/20890498/f871910a-07f6-41c4-8d9f-9f034311e060)

**Comment by 7MinSec** [comment]
Yep I think this is an issue with the combo of python and/or CME on the machine.  I'll make sure to mention in class that the "double Enter" might need to happen when CME gets stuck.
