### ISSUE TITLE
relatively small issue but multiple choice quiz doesn't allow multiple answers

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#69]
**Where is the problem happening**
https://7minsec.teachable.com/courses/lplite2/lectures/46224725

**Describe the problem**
Quiz (question 2) says system(s), implying multiple choice, but it only allows you to select one answer. Realistically speaking there's only one correct answer so it's not that big of a deal, but thought I'd add that here.

**To Reproduce**
Scroll to the bottom of Day 1 "Active Directory dumpster diving", go to question two, and try selecting two answers.

**Expected behavior**
Should allow more than one answer

**Screenshots**
![image](https://github.com/7MinSec/LPLITE/assets/95602421/ebed526c-6d23-484d-b9a4-f4c8c86523b5)

**Comment by 7MinSec** [comment]
Ahhh good catch man!  The "kind of right" answer is DEV01 because that's the one I want students to focus on later in the course.  BUT, you're absolutely spot on in that the DC is also config'd for unconstrained delegation.

Fixed.
