### ISSUE TITLE
Rephrase directions for accuracy (Network share enumeration)

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#7]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224726

**Describe the problem**

Probably start with *Run PowerShell*, then have the *Browse to C:\Users\Public...* step afterwards. No biggie though.

![image](https://user-images.githubusercontent.com/1383363/234367523-64010028-4673-4fb5-85dd-0470bdae3b21.png)

**Comment by 7MinSec** [comment]
I like the consistency.  I added instructions to remind folks to get to a command prompt and into PS before proceeding.
