### ISSUE TITLE
Need clearer instructions to say to do privesc

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#70]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224734

**Describe the problem**
Just the wording on this. It feels like it's more of a pointer for "when you attempt privesc", along with asking a question of you how think you could do privesc. To me it didn't seem like I needed to actually do anything until day 2 when it said "we have local admin" and I was like.. oh shoot! Anyway, it's kind of a minor thing but something I noticed.

**Expected behavior**
Maybe add a header or line of text indicating that you should go do it..

**Screenshots**
![image](https://github.com/7MinSec/LPLITE/assets/95602421/fad2b0ea-3e74-40ce-82f7-8f874e537066)

**Comment by 7MinSec** [comment]
OK I edited the quiz to hopefully make this more straightforward:

![image](https://github.com/7MinSec/LPLITE/assets/17596787/4f81372a-98e3-4d64-a92f-a97da319e447)
