### ISSUE TITLE
Two Tiny Typos

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#71]
**The first one:**
https://7minsec.teachable.com/courses/2053747/lectures/46224738
On step one it says "Browser to C:\Users..."

**The second one:**
https://7minsec.teachable.com/courses/lplite2/lectures/46224757
On the second big paragraph under `Using Hashcat`, it says "and the mode for the is 1000."

**Comment by 7MinSec** [comment]
Sheesh, you could get a job as an editor for the New York Times!

Both fixed.
