### ISSUE TITLE
Explanation of how we got the password for password spraying

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#72]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224744

**Describe the problem**
In "Password spraying with Rubeus", after the sample formats for using rubeus, it jumps right into password spraying with the password "summer2021". No matter what, I couldn't remember seeing this password and it's not in my notes. Did I miss something?

**Expected behavior**
Maybe add something like "remember this password from <blank>"

**Screenshots**
![image](https://github.com/7MinSec/LPLITE/assets/95602421/f9922390-1bda-476c-b18e-b7a7ccafd954)

**Comment by 7MinSec** [comment]
The summer passwords are just examples to play with Rubeus.
