### ISSUE TITLE
Minor continuity error in Enter-PSSession command

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#73]
*Minor continuity error in Enter-PSSession command*

**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224760

**Describe the problem**
Around the 5th paragraph, it says "Note that after the -Credential flag we're authenticating with tt-it01 and not tangent because we're trying to login...." This is saying to log in with `tt-it01\localadmin`. 

Then a few pictures down it shows logging in with `localhost\localadmin`. 
![image](https://github.com/7MinSec/LPLITE/assets/95602421/8a66a39b-46a5-420f-9c73-55c4a54b618a)

Both work just fine, just noticed that it explains using tt-it01 but later shows using localhost

**Comment by 7MinSec** [comment]
Phew, good catch.  I'll just make sure I mention in the live version that both *localhost* and *TT-IT01* will work.
