### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#74]
https://7minsec.teachable.com/courses/2053747/lectures/46808970

Under part two, it says "This command sets up the ntlmrelayx.py program, enables SMB support, disables the SMB server (because lsarelayx.exe and sets a target of TT-APP01 with -t smb://tt-app01)."

`because lsarelayx.exe and sets a target of` (just the "and")

**Comment by 7MinSec** [comment]
Yeah thanks.  That sentence was a mess.  I cleaned it up!
