### ISSUE TITLE
How did we know about this password?

### ISSUE THREAD

**Issue by pixlproject** [7MinSec/LPLITE#75]
**Where is the problem happening**
https://7minsec.teachable.com/courses/2053747/lectures/46224744

**Describe the problem**
I was just having trouble understanding where we got the password `Summer2021` for password spraying. This wasn't the password for asreproast or kerberoast, so I'm not sure where we got it from. 

I'm not sure if this is a "bug" or issue or something, or if it's just me missing something, but I decided to open an issue anyway.

**Screenshots**
![image](https://github.com/7MinSec/LPLITE/assets/95602421/33a57a23-b80a-49c8-8dc8-406e8331a382)

**Comment by 7MinSec** [comment]
This summer password is just an example to spray with.  It didn't come from a particular place.
