### ISSUE TITLE
Important typo in *Unquoted service paths* directions

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#8]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
https://7minsec.teachable.com/courses/2053747/lectures/46224733

**Describe the problem**
A trailing slash to `icacls` results in an error:
![image](https://user-images.githubusercontent.com/1383363/234373920-315c4760-a668-481d-9709-82840f4700e0.png)

And the lab directions say to include them:
![image](https://user-images.githubusercontent.com/1383363/234374027-247d6b25-477b-4f1b-aa2a-3c36a54a938e.png)

Remove the trailing slashes and all is good

**Comment by 7MinSec** [comment]
Excellent find.  Fixed.
