### ISSUE TITLE
OpenSSL not installed and not called out for installation (CrackMapExec: validating domain credentials)

### ISSUE THREAD

**Issue by jeffmcjunkin** [7MinSec/LPLITE#9]
**Where is the problem happening**
Provide the Teachable curriculum URL that corresponds with the issue you're reporting.
https://7minsec.teachable.com/courses/2053747/lectures/46224742

**Describe the problem**
![image](https://user-images.githubusercontent.com/1383363/234383181-95dc801b-1fa8-422c-aa48-0e4fc6179379.png)

I'll see how big a deal this is later, though the installer is present: 

![image](https://user-images.githubusercontent.com/1383363/234383312-bd4bd822-7334-4eaa-8b49-76277fea0ea1.png)

**Comment by 7MinSec** [comment]
Ah.  I have Win64OpenSSL_Light-3_1_0 in there for a future enhancement of getting ADCS vulns baked into the environment.  I'll open a separate issue to remind myself to get that going...but for now I think CME works fine without the SSL part.
